[package]
name = "atha-reader-host"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
atha-backend = { path = "../../backend/atha-backend" }

[target.'cfg(windows)'.dependencies]
tao = { version = "=0.36.0", default-features = false, features = ["rwh_06"] }
wry = { version = "=0.56.0", default-features = false, features = ["os-webview"] }

[lints]
workspace = true
