[package]
name = "atha-reader-app"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[lib]
name = "atha_reader_app"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
atha-backend = { path = "../../../backend/atha-backend" }
log = "0.4"
serde = { version = "1", features = ["derive"] }
tauri = { version = "2", features = [] }
tauri-plugin-dialog = "2"
tauri-plugin-fs = "2"
tauri-plugin-log = "2"

[target.'cfg(windows)'.dependencies]
atha-reader-host = { path = "../../atha-reader-host" }

[lints]
workspace = true
